repos:
  - repo: https://github.com/psf/black
    # Black version.
    rev: 23.3.0 
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.278
    hooks:
      - id: ruff
